//! # lodestar-ann-core
//!
//! Foundational building blocks for the Lodestar approximate-nearest-neighbour
//! engine:
//!
//! * [`distance`] — L2 / cosine / inner-product kernels with runtime CPU
//!   dispatch (NEON on aarch64, AVX2+FMA on x86_64, portable scalar fallback).
//! * [`quantize`] — 8-bit scalar quantization (SQ8) for memory-efficient
//!   storage of dense vectors.
//! * [`pq`] — product quantization with a k-means++ / Lloyd codebook trainer
//!   and asymmetric distance computation (ADC) lookup tables.
//! * [`brute`] — exact k-nearest-neighbour search, used as the ground-truth
//!   oracle in recall tests and as a fallback for tiny collections.
//!
//! Everything in this crate is deterministic: given the same inputs and seed,
//! results are bit-identical across runs and platforms. Reproducibility is a
//! hard requirement because every published benchmark number in this project is
//! regenerated by CI from a fixed seed.
//!
//! ```
//! use lodestar_ann_core::{brute, distance, types::Metric};
//!
//! let data = [0.0f32, 1.0, 10.0, 10.0];
//! let hits = brute::knn(&data, 2, 2, Metric::L2, &[0.1, 1.1], 1, None);
//! assert_eq!(hits[0].id, 0);
//! assert!(distance::l2_squared(&[0.0, 1.0], &[0.1, 1.1]) < 0.1);
//! ```

#![forbid(unsafe_op_in_unsafe_fn)]
#![warn(missing_docs)]
#![warn(clippy::all)]

pub mod brute;
pub mod distance;
pub mod error;
pub mod pq;
pub mod quantize;
pub mod rng;
pub mod types;

pub use error::{Error, Result};
pub use rng::Rng;
pub use types::{Candidate, Hit, Metric, l2_normalize};
